// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MysqlApi.Persistencia;

#nullable disable

namespace MysqlApi.Migrations
{
    [DbContext(typeof(ContextoPlanta))]
    [Migration("20220528194608_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MysqlApi.Modelo.Planta", b =>
                {
                    b.Property<int>("IdPlanta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdPlanta");

                    b.ToTable("Plantas");
                });
#pragma warning restore 612, 618
        }
    }
}
