// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PostgresqlApi.Persistencia;

#nullable disable

namespace PostgresqlApi.Migrations
{
    [DbContext(typeof(ContextoAnimal))]
    partial class ContextoAnimalModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PostgresqlApi.Modelo.Animal", b =>
                {
                    b.Property<int>("IdAnimal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnimal"));

                    b.Property<string>("Clase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Familia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Orden")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAnimal");

                    b.ToTable("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
